ENGINEERING = set([
    'EBME','ECES','ECHE','ECIV',
    'ECMP','EEAP','EECS','EIND',
    'EMAC','EMAE','EMCH','EMSE',
    'ENGR','ESYS','EMAC','EFTS',
    'CMPS','ESCI','EPOM'
])
SAGES = set([
    'USSY',"USSO","USNA","FSSY",
    "FSNA","FSCC","FSSO","FSCS",
    "USFS","FSTS",
])
ARTS_AND_SCIENCES = set([
    "AMST","HSTY","ANTH","INTL"
    "ARTS","ITAL","ARAB","JAPN",
    "ASTR","LATN","BIOL","MATH",
    "CHEM","MUSC","CHIN","PHIL",
    "CHST","PHYS","CLSC","POSC",
    "COGS","PSCL","COSI","RLGN",
    "DANC","RUSN","ENGL","SOCI",
    "ETHS","SPAN","FRCH","STAT",
    "GEOL","THTR","GREK","WLIT",
    "GRMN","WMST","HBRW","WSTD",
    "ASIA","JDST","ESTD","APMU",
    "MUHI","EDUC","CMPL","ARTS",
    "GERO","LITR","MUED","MUTH",
    "ARTH","MUGN"
])
WEATHERHEAD = set([
    'ACCT', 'BAFI', 'ECON', 'LHRP', 
    'PLCY', 'MKMR', 'MIDS', 'OPMT', 
    'OPRE', 'ORBH', 'MGMT', 'HSMC',
    'EDMP', 'ENTP', 'BIOS', 'EMBA',
    'QUMM', 'BLAW', 
])
MEDICAL = set([
    'PATH','BETH','NTRN','BIOC',
])
MANDEL = set([
    'SASS',
])
KNOWN_ORPHAN = set([
    'ARSC'
])
HARD_SCIENCES = set([
    'ADHT', 'ANAT', 'ARTK', 'ASTR', 'BASC', 'BETH', 'BIOC', 'BIOL', 'BIOM', 'CBIO', 'CHEM', 'CLBY', 
    'CMPS', 'DBIO', 'EBME', 'ECES', 'ECHE', 'ECIV', 'ECMP', 'EEAP', 'EECS', 'EIND', 'EMAC', 'EMAE', 
    'EMSE', 'EPBI', 'ESCI', 'ESYS', 'ETHC', 'GENE', 'GEOL', 'GEOM', 'MAPH', 'MASS', 'MATH', 'MBIO', 
    'MIDS', 'MMED', 'NEUR', 'NEUS', 'NSCI', 'PHOL', 'PHYS', 'RBIO', 'STAT'])
SOFT_SCIENCES = set([
    'ABLE', 'ACCT', 'AMST', 'ANTH', 'APMU', 'ARAB', 'ARTH', 'ARTS', 'ASCV', 'ASIA', 'BAFI', 'BLAW', 
    'CHIN', 'CHST', 'CIAR', 'CLSC', 'CMPL', 'COGS', 'COSI', 'DANC', 'ECON', 'EDJC', 'EDMP', 'EDUC', 
    'EMBA', 'ENGL', 'ENTP', 'ERAS', 'ESTD', 'ETHS', 'EVHS', 'FRCH', 'GERM', 'GREK', 'GRMN', 'HBRW', 
    'HLTH', 'HSMC', 'HSST', 'HSTY', 'HUMN', 'IIME', 'INTC', 'INTH', 'INTL', 'ITAL', 'JAPN', 'JDST', 
    'LAPP', 'LATN', 'LAWS', 'LCAN', 'LHRP', 'LIBS', 'LITR', 'LLM ', 'LMON', 'MAND', 'MBAC', 'MGMT', 
    'MKMR', 'MLIT', 'MPHP', 'MUAP', 'MUAR', 'MUCP', 'MUDE', 'MUED', 'MUEN', 'MUGN', 'MUHI', 'MULI', 
    'MUPD', 'MURP', 'MUSC', 'MUSD', 'MUTH', 'NORG', 'NTRN', 'OPMT', 'OPRE', 'ORBH', 'PHCP', 'PHED', 
    'PHIL', 'PLCY', 'POSC', 'PRAC', 'PSCL', 'PSY7', 'PSYC', 'PSYY', 'QUMM', 'READ', 'RLGN', 'RUSN', 
    'SOCI', 'SPAN', 'SSBT', 'THTR', 'WLIT', 'WMST', 'WSTD'
])

subject_codes = {
    'ABLE': "ABILITY BASED LEARNING ENVIR     ",
    'ACCT': "ACCOUNTING                       ",
    'ACES': "ACAD & COMPUT EXCELLENCE SEM     ",
    'ADHT': "ADOLESCENT HEALTH                ",
    'AMBM': "AMBULATORY MEDICINE              ",
    'AMST': "AMERICAN STUDIES                 ",
    'ANAT': "ANATOMY                          ",
    'ANES': "ANESTHESIOLOGY                   ",
    'ANTH': "ANTHROPOLOGY                     ",
    'APMU': "APPLIED MUSIC                    ",
    'ARAB': "ARABIC                           ",
    'ARSC': "COLLEGE SCHOLARS PROGRAM         ",
    'ARTH': "ART HISTORY                      ",
    'ARTK': "COMPUTERS IN VISUAL ARTS         ",
    'ARTS': "ART STUDIO                       ",
    'ASCV': "ASIAN CIVILIZATION               ",
    'ASIA': "ASIAN STUDIES                    ",
    'ASTR': "ASTRONOMY                        ",
    'BAFI': "BANKING AND FINANCE              ",
    'BASC': "BASIC SCIENCE CURRICULUM         ",
    'BETH': "BIOETHICS                        ",
    'BIOC': "BIOCHEMISTRY                     ",
    'BIOL': "BIOLOGY                          ",
    'BIOM': "BIOMETRY                         ",
    'BIOS': "BIOSCIENCE ENTREPRENEURSHIP      ",
    'BLAW': "BUSINESS LAW                     ",
    'BOCR': "BASIS OF CLINICAL REASONING      ",
    'BSTP': "BIOMEDICAL SCIENCES TRAIN PROG   ",
    'CAPG': "CORE ACADEMIC PROGRAM            ",
    'CARD': "CARDIOLOGY                       ",
    'CARE': "PRIMARY CARE COURSES             ",
    'CBIO': "CELLULAR & MOLECULAR BIOL        ",
    'CFNU': "COMMUNITY FRONTIER NURSING       ",
    'CHEM': "CHEMISTRY                        ",
    'CHIN': "CHINESE                          ",
    'CHST': "CHILDHOOD STUDIES                ",
    'CIAR': "CLEVELAND INSTITUTE OF ART       ",
    'CLBY': "CELL BIOLOGY                     ",
    'CLIN': "CLINICAL CURRICULUM              ",
    'CLMI': "CLINICAL MED AND INTERNSHIPS     ",
    'CLSC': "CLASSICS                         ",
    'CMED': "CLINICAL RESEARCH - CCLCM        ",
    'CMPL': "COMPARATIVE LITERATURE           ",
    'CMPS': "COMPUTING/INFORMATION SCIENCE    ",
    'COGS': "COGNITIVE SCIENCE                ",
    'COLS': "GRADUATE SUMMER RESEARCH         ",
    'COOP': "COOPERATIVE EDUCATION            ",
    'COSI': "COMMUNICATION SCIENCES           ",
    'CRSP': "CLINICAL RESRCH SCHOLARS PROG    ",
    'DANC': "DANCE                            ",
    'DBIO': "DEVELOPMENTAL BIOLOGY            ",
    'DENC': "DENTISTRY - CLINICAL             ",
    'DEND': "DENTISTRY - DIDACTIC             ",
    'DENF': "DENTISTRY - FACULTY              ",
    'DENT': "DENTISTRY                        ",
    'DERM': "DERMATOLOGY                      ",
    'DGMS': "GENERAL MEDICAL SCIENCES         ",
    'EBME': "BIOMEDICAL ENGINEERING           ",
    'ECES': "COMPUTER ENGR AND SCIENCE        ",
    'ECHE': "CHEMICAL ENGINEERING             ",
    'ECIV': "CIVIL ENGINEERING                ",
    'ECLE': "EARLY CLINICAL EXPERIENCE        ",
    'ECMP': "COMPUTER ENGINEERING             ",
    'ECON': "ECONOMICS                        ",
    'EDJC': "EDUCATION - JOHN CARROLL UNIV    ",
    'EDMP': "EXECUTIVE DOCTOR OF MANAGEMENT   ",
    'EDUC': "EDUCATION                        ",
    'EEAP': "ELEC ENGR & APPLIED PHYSICS      ",
    'EECS': "ELECTRICAL ENGR & COMPUTER SCI   ",
    'EIND': "INDUSTRIAL ENGINEERING           ",
    'EMAC': "MACROMOLECULAR/POLYMER SCIENCE   ",
    'EMAE': "MECHANICAL & AEROSPACE ENGR      ",
    'EMBA': "EXECUTIVE MBA                    ",
    'EMMD': "EMER MEDICINE/INTEN CARE         ",
    'EMSE': "MATERIALS SCIENCE & ENGINEERNG   ",
    'ENDO': "ENDOCRINOLOGY                    ",
    'ENGL': "ENGLISH                          ",
    'ENGR': "ENGINEERING SCIENCE              ",
    'ENTP': "ENTREPRENEURSHIP                 ",
    'EPBI': "EPIDEMIOLOGY & BIOSTATISTICS     ",
    'EPOM': "PRACT ORIENTED ENGR MAST PROG    ",
    'EQUI': "OUT-OF-TOWN EQUIVALENCY          ",
    'ERAS': "ERASMUS                          ",
    'ESCI': "SYSTEMS CTRL & INDUSTRIAL ENGR   ",
    'ESTD': "ENVIRONMENTAL STUDIES            ",
    'ESYS': "SYSTEMS ENGINEERING              ",
    'ETHC': "BIOMEDICAL ETHICS                ",
    'ETHS': "ETHNIC STUDIES                   ",
    'EVHS': "ENVIRONMENTAL HEALTH SCIENCES    ",
    'EXAM': "EXAMINATION MASTER/PH.D          ",
    'EXCH': "INT'L EXCHANGE PROGRAM           ",
    'FAMD': "FAMILY MEDICINE                  ",
    'FGFM': "FAIRVIEW GEN HOSP-FAM MED        ",
    'FMCL': "FREE MEDICAL CLINIC OF CLEVE     ",
    'FRCH': "FRENCH                           ",
    'FSCC': "FIRST SEMINAR COMMON CURRIC      ",
    'FSCS': "FIRST SEMINAR CONT  SEMESTER     ",
    'FSNA': "FIRST SEMINAR NATURAL WORLD      ",
    'FSSO': "FIRST SEMINAR SOCIAL WORLD       ",
    'FSSY': "FIRST SEMINAR SYMBOLIC WORLD     ",
    'FSTS': "FIRST SEMINAR TRANSFER SUPPLEM   ",
    'GAST': "GASTROENTEROLOGY                 ",
    'GEMD': "GERIATRIC MEDICINE               ",
    'GENE': "GENETICS                         ",
    'GEOL': "GEOLOGY                          ",
    'GEOM': "GEOGRAPHIC MEDICINE              ",
    'GERM': "GERMAN                           ",
    'GERO': "GERONTOLOGICAL STUDIES           ",
    'GREK': "GREEK                            ",
    'GRMN': "GERMAN                           ",
    'GVHA': "GLENVILLE HEALTH ASSOCIATION     ",
    'HBRW': "HEBREW                           ",
    'HDEV': "INTERDISC PROG: HUM DEVELOPMNT   ",
    'HEMA': "HEMATOLOGY-ONCOLOGY              ",
    'HLTH': "COMMUNITY HEALTH                 ",
    'HNHC': "HOUGH NORWOOD HEALTH CENTER      ",
    'HRAM': "HURON RD HOSP AMBUL MED          ",
    'HSMC': "HEALTH SYSTEMS MANAGEMENT        ",
    'HSST': "HIST OF SCIENCE & TECHNOLOGY     ",
    'HSTY': "HISTORY                          ",
    'HUMN': "HUMANITIES                       ",
    'IBIS': "INTEGRATED BIOLOGICAL SCIENCES   ",
    'IBMS': "INTEGRATED BIOLOGICAL STUDIES    ",
    'IDHS': "INTERDISCIPLINARY HEALTH STUD    ",
    'IIME': "INST FOR INTEGR OF MGMT & ENGR   ",
    'IMMU': "IMMUNOLOGY AND INFECTIOUS DIS    ",
    'INTC': "INTENSIVE CARE                   ",
    'INTH': "INTERNATIONAL HEALTH             ",
    'INTL': "INTERNATIONAL STUDIES            ",
    'ITAL': "ITALIAN                          ",
    'JAPN': "JAPANESE                         ",
    'JDST': "JUDAIC STUDIES                   ",
    'JRAB': "JUNIOR YEAR ABROAD               ",
    'LAPP': "LAW & PUBLIC POLICY              ",
    'LATN': "LATIN                            ",
    'LAWS': "LAW                              ",
    'LCAN': "CANADIAN LAW COURSES             ",
    'LHRP': "LABOR & HUMAN RESOURCE POLICY    ",
    'LIBS': "LIBRARY SCIENCE                  ",
    'LITR': "LITERATURE                       ",
    'LLM ': "LL M  TAX PROGRAM                ",
    'LMON': "MONTREAL LAW COURSES             ",
    'MANC': "UNIVERSITY OF MANCHESTER         ",
    'MAND': "MANDEL CENTER                    ",
    'MAPH': "MATHEMATICAL PHYSICS             ",
    'MASS': "MEDICINE AND SOCIAL STRUCTURES   ",
    'MATH': "MATHEMATICS                      ",
    'MBAC': "MBA CORE                         ",
    'MBIO': "MOLECULAR BIOL & MICROBIOLOGY    ",
    'MCCT': "METRO CLEMENT CENTER             ",
    'MEDC': "MEDICINE CORE CLERKSHIP          ",
    'MEDG': "GENERAL MEDICINE                 ",
    'MEDT': "MEDICAL TECHNOLOGY               ",
    'MGMT': "MANAGEMENT                       ",
    'MHAM': "METRO HEALTH - AMBUL. MED.       ",
    'MHAP': "METRO HEALTH - AMBUL. PED.       ",
    'MHFM': "METRO HEALTH - FAM. MED.         ",
    'MIDS': "INFORMATION SYSTEMS              ",
    'MISC': "MISCELLANEOUS                    ",
    'MKMR': "MARKETING                        ",
    'MLIT': "MOD FOREIGN LIT & MOD LANG       ",
    'MMED': "MOLECULAR MEDICINE               ",
    'MPHP': "PUBLIC HEALTH                    ",
    'MSFM': "MT SINAI MED CENTER-FAM MED      ",
    'MSOD': "MANIFESTATIONS OF DISEASE        ",
    'MSPC': "MT SINAI MED CTR-PRIM CARE       ",
    'MSTP': "MED SCIENTIST TRAINING PROG      ",
    'MUAP': "APPLIED MUSIC                    ",
    'MUAR': "MUSIC, AUDIO RECORDING           ",
    'MUCP': "MUSIC COMPOSITION                ",
    'MUDE': "MUSIC, DALCROZE/EURYTHMICS       ",
    'MUED': "MUSIC EDUCATION                  ",
    'MUEN': "MUSIC, ENSEMBLES                 ",
    'MUGN': "MUSIC, GENERAL/MISC              ",
    'MUHI': "MUSIC HISTORY                    ",
    'MULI': "MUSIC LITERATURE                 ",
    'MUPD': "MUSIC, PEDAGOGY                  ",
    'MURP': "MUSIC, REPERTOIRE                ",
    'MUSC': "MUSIC                            ",
    'MUSD': "DOCTOR MUSICAL ARTS              ",
    'MUTH': "MUSIC THEORY                     ",
    'MVIR': "MOLECULAR VIROLOGY TRAIN  PRG    ",
    'NEUM': "NEUROLOGICAL MEDICINE            ",
    'NEUR': "NEUROSCIENCES                    ",
    'NEUS': "NEUROSCIENCES                    ",
    'NORG': "NOEWAGIAN SCHOOL OF MGMT         ",
    'NSCI': "NEUROSCIENCES                    ",
    'NTRN': "NUTRITION                        ",
    'NUAN': "NURSING ANESTHESIOLOGY           ",
    'NUND': "DOCTOR OF NURSING                ",
    'NUNI': "NURSING INFORMATICS              ",
    'NUNP': "NURSE PRACTITIONER               ",
    'NURS': "NURSING                          ",
    'OBGC': "OB/GYN CORE CLERKSHIP            ",
    'OPMT': "OPERATIONS MANAGEMENT            ",
    'OPRE': "OPERATIONS RESEARCH              ",
    'OPTH': "OPTHALMOLOGY                     ",
    'ORBH': "ORGANIZATIONAL BEHAVIOR          ",
    'ORTH': "ORTHOPAEDIC SURGERY              ",
    'OTHR': "OTHER                            ",
    'OTOL': "OTOLARYNGOLOGY                   ",
    'OUTC': "OUT OF TOWN CORE CLERKSHIP       ",
    'PATH': "PATHOLOGY                        ",
    'PBPG': "PATIENT BASED PROGRAM            ",
    'PCHP': "PRIMARY CARE HEALTH POLICY       ",
    'PCPC': "PRIMARY CARE HEALTH POLICY       ",
    'PEDC': "PEDIATRIC CORE CLERKSHIP         ",
    'PEDS': "PEDIATRICS                       ",
    'PGOD': "PATHOGENSIS OF DISEASE           ",
    'PHCP': "HEALTH POLICY                    ",
    'PHED': "PHYSICAL EDUCATION               ",
    'PHIL': "PHILOSOPHY                       ",
    'PHOL': "PHYSIOLOGY & BIOPHYSICS          ",
    'PHRM': "PHARMACOLOGY                     ",
    'PHYS': "PHYSICS                          ",
    'PLCY': "MANAGEMENT POLICY                ",
    'POSC': "POLITICAL SCIENCE                ",
    'PRAC': "PRACTICUM                        ",
    'PSCL': "PSYCHOLOGY                       ",
    'PSYC': "PSYCHIATRY CORE CLERKSHIP        ",
    'PSYY': "PSYCHIATRY                       ",
    'PSY7': "PSYCHIATRY AT BRECKSVILLE        ",
    'PULM': "PULMONARY MEDICINE               ",
    'QUMM': "QUANTITATIVE METHODS IN MGMT     ",
    'RADI': "RADIOLOGY                        ",
    'RASE': "RESEARCH & SPECIAL ELECTIVES     ",
    'RBAM': "RAINBOW BABIES & CHILD AMB       ",
    'RBIO': "REPRODUCTIVE BIOLOGY             ",
    'READ': "READING & LEARNING STRATEGIES    ",
    'REHA': "REHAB MED/OCCUPATIONAL HLTH      ",
    'RENL': "RENAL/NEPHROLOGY                 ",
    'RESC': "RESEARCH CURRICULUM              ",
    'RHEU': "CLINICAL RHEUMATOLOGY            ",
    'RLGN': "RELIGION                         ",
    'RSCH': "GRADUATE SUMMER RESEARCH         ",
    'RUSN': "RUSSIAN                          ",
    'SASS': "SASS                             ",
    'SLAM': "ST LUKE'S AMBULATORY MEDICINE    ",
    'SMAB': "SEMESTER IN ABSENTIA             ",
    'SOCI': "SOCIOLOGY                        ",
    'SPAN': "SPANISH                          ",
    'SPCL': "SUB-SPECIALITIES                 ",
    'SPPP': "SPPP - PROBLEMS/POLICY PROGRAM   ",
    'SPSM': "SPECIAL STUDIES IN MEDICINE      ",
    'SRAB': "SENIOR IN ABSENTIA               ",
    'SRCH': "SRCH - S W RESEARCH              ",
    'SSBT': "SSBT - SOCIOBEHAVIORAL THEORY    ",
    'SSPL': "SURGICAL SUB-SPECIALITIES        ",
    'SSWM': "SSWM - SOCIAL WORK METHODS       ",
    'STAT': "STATISTICS                       ",
    'SURC': "SURGERY CORE CLERKSHIP           ",
    'SURG': "SURGERY                          ",
    'SVAM': "ST VINCENT CHARITY-AMBUL MED     ",
    'SWBC': "SASS - SW METH ELEC B/C STREAM   ",
    'THTR': "THEATER ARTS                     ",
    'TRAN': "TRANSFUSION MEDICINE             ",
    'UCAP': "SAGES CAPSTONE EXPERIENCE        ",
    'UGSP': "UNDERGRADUATE SCHOLARS PROG      ",
    'UHFP': "UNIVERSITY HOSP FAMILY PRACT     ",
    'UNEL': "UNLISTED ELECTIVE                ",
    'UNIV': "UNIVERSITY STUDIES               ",
    'UROL': "UROLOGY                          ",
    'USFS': "UNIV SEMINARS FIRST SEMINAR      ",
    'USHC': "UNIVERSITY SUBURBAN HLTH CNTR    ",
    'USNA': "THINK ABOUT THE NATURAL WORLD    ",
    'USSO': "THINK ABOUT THE SOCIAL WORLD     ",
    'USSY': "THINK ABOUT THE SYMBOLIC WORLD   ",
    'WASH': "WASHINGTON SEMESTER              ",
    'WKAB': "WORK IN ABSENTIA                 ",
    'WLIT': "WORLD LITERATURE                 ",
    'WMST': "WOMEN'S STUDIES                  ",
    'WSTD': "WOMEN'S STUDIES                  ",
    'YES ': "PRE/COREQ(S) APPLY               ",
}
# Clean subject code data
for k, v in subject_codes.iteritems():
    subject_codes[k] = subject_codes[k].strip()